version: '2'
services:
  peervpn:
    cap_add:
    - NET_ADMIN
    image: thedrhax/rancher-peervpn:v0.3
    environment:
      VPN_KEY: ${VPN_KEY}
      VPN_NAME: ${VPN_NAME}
      VPN_PEERS: ${VPN_PEERS}
      VPN_PORT: ${VPN_PORT}
      VPN_INTERFACE: ${VPN_INTERFACE}
      RANCHER_AGENT: ${RANCHER_AGENT}
    devices:
    - /dev/net/tun:/dev/net/tun:rwm
    stdin_open: true
    network_mode: host
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    tty: true
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label_ne: peervpn=false
      io.rancher.scheduler.global: 'true'
